name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容...
      uses: actions/checkout@v4
      
    - name: 登录DockerHub...
      uses: docker/login-action@v3
      with:
        username: ${{ sercets.DOCKER_HUB_USERNAME }}
        password: ${{ sercets.DOCKER_HUB_TOKEN }}
        
    - name: 构建并推送...
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: 1ynn/poe2openai:latest
